// src/app/layout.tsx or src/app/layout.js

// Providers（認証・状態管理・テーマ管理など）をまとめたコンポーネントを読み込み
import { Providers } from "./providers";

import type { Metadata } from "next"; // メタデータ型のインポート
import { Geist, Geist_Mono } from "next/font/google"; // Google Fonts の Geist フォントをインポート

// グローバルCSSの読み込み
import "./globals.css";

// Google Fonts（Geistフォント）を読み込み
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Google Fonts（Geist Monoフォント）を読み込み
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Meta情報（タイトルや説明文など）
export const metadata: Metadata = {
  title: "TODO管理リスト",
  description: "Generated by create next app",
};

// すべてのページに共通するレイアウト
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // HTML 文書のルート設定
    <html lang="en">
      {/* body 全体のレイアウトに Providers を適用 */}
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* グローバルに適用する Provider（認証、状態管理など） */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
